sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mkfx4frDYMEi0pXrKFcwbZ1DmcYNagKC5UWP4AMD517ubHJVGbi678Q1DY/6r+n+0HiUrPuT16F1Vt0XU/q7LrzqQqbQE+FPz3ZUvBjUrjXnrPvPFf7SAl+/otXVbfTI8+B9yXyXTqtaqR7O0ptNG/FTDP2g0xvVGFa/FFYo7jB7T/KCs9vfDu+i521Pii/BEPfscYoUa8ZsrOo2GM4GUn6nip/T3O3uDdIElTHBzMaahdgTkf2K/H+zdFUAV/bqHIHQhJZd5NawHTjSfMTIZxSo8ph6t2DA7wgEstfTWzM5eFtJtopTFB2indePKkeBnoFteF1QiI3m/m6sm8NaD5p8/85Vw8Z8icmZbmttk9jzgJUsfUd4AtcJMEqS9O5g3ssfqWcEw6FJgEa6w8OksEius7nIgzQEoBeSVpTomq79KVg1i+qGaerNx9rHJbQa70Ean6obLf82KyFkBXC/u0iJ0HbIrDVh2O4aA0Q7tlrbPWsQsKOUB3IZo8CZZdA5tEXnsht+yKiR1tcWo8Z5mwFjCSeL46NGdagYvBJPywurDnKAmUM9Ab58GjvcOu6DmsjOPJ7rGWwMc1B+w8jgSJXC9nfZbkMgu/vIZa4jYqIAx7tjAkQ48ZKaNw/zJGq/NIKvmYtSwICvcaHTkbBOl8DtZ8mgRF+7O/6nOORUSko=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Rise-of-the-Dutch-Republic-Volume-26-1577-part-III_4828
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy